esphome:
  name: epaperinfodisplay
  on_boot:
    - output.turn_on: led_2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ../esphome/components/

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: ""

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true # connect without scanning first, should save time

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret fallback_ap_password

  on_connect:
    - output.turn_on: led_1
    - script.execute: download_image_script
  on_disconnect:
    - output.turn_off: led_1

captive_portal:

output:
  - platform: gpio
    pin: 7
    id: led_1
  - platform: gpio
    pin: 8
    id: led_2

spi:
  clk_pin:
    number: 2
    ignore_strapping_warning: true
  mosi_pin: 3

globals:
  - id: image_download_ok
    type: 'bool'
    restore_value: no
    initial_value: 'false'

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

display:
  id: epaper
  platform: pervasive_displays_epaper
  update_interval: never # update is explicity called
  reset_pin: 10
  busy_pin: 4
  enable_pin: 6
  model: "7.41in"
  dc_pin: 0
  cs_pin: 1
  rotation: 270°
  lambda: |-
    if (id(image_download_ok)) {
      //draw only the image
      it.image(0, 0, id(frame_image), COLOR_OFF, COLOR_ON);
    } else {
      //draw error message
      it.fill(COLOR_ON);
      it.print(400, 50, id(roboto_20), COLOR_OFF, TextAlign::CENTER, "Error");
      it.print(400, 100, id(roboto_20), COLOR_OFF, TextAlign::CENTER, "Image Download failed");
    }

online_image:
  - url: !secret image_url
    id: frame_image
    format: PNG
    # request_headers: # Send current battery voltage as header
    #   X-Bat-Voltage: !lambda |-
    #     return id(vcc_sensor).state;
    #placeholder
    type: BINARY
    buffer_size: 16384 # 16kB buffer, otherwise fails with out of memory
    on_download_finished:
      - globals.set:
          id: image_download_ok
          value: 'true'
      - script.execute: update_display_script
    on_error:
      - globals.set:
          id: image_download_ok
          value: 'false'
      - script.execute: update_display_script

http_request: # required by online_image
  verify_ssl: false #not supported on the Arduino framework

deep_sleep:
  run_duration: 1h # we explicitly enter deep sleep
  sleep_duration: 24h # TODO: Add a time component and use until: to wakeup in the night

script:
  - id: download_image_script
    then:
      # - component.update: vcc_sensor
      # - logger.log: # DEBUG
      #     format: "VCC is %.1f V"
      #     args: ['id(vcc_sensor).state']
      - component.update: frame_image
  - id: update_display_script
    then:
      - wifi.disable: # disable wifi after image was downloaded
      - component.update: epaper
      - script.execute: enter_deepsleep_script
  - id: enter_deepsleep_script
    then:
      - output.turn_off: led_2
      - deep_sleep.enter

# sensor:
#   id: vcc_sensor
#   platform: adc
#   pin: 5 # for testing, the real pin 5 cannot be used when WiFi is active...
#   attenuation: auto
#   update_interval: never
